server:
  port: 1908
eureka:
  instance:
    hostname: localhost
  client:
    # 声明是否将自己的信息注册到Eureka服务器,默认值为true
    register-with-eureka: false
    # 是否到Eureka服务器中抓取注册信息
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/